---
title: "Codebook"
output: html_document
---

##Summary
The data is derived from an experiment where volunteers performed different physical activities, while wearing a device which recorded linear acceleration and angular velocity. The study was performed by:

_Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012_

##Study Design
###Experimental Design
The experiments were carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING\_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, 3-axial linear acceleration and 3-axial angular velocity was captured at a constant rate of 50Hz. The experiments were video-recorded to label the data manually. The obtained dataset was randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

###The Raw Data Set
The data recorded within the raw data set contained:

* Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
* Triaxial Angular velocity from the gyroscope. 
* A 561-feature vector with time and frequency domain variables. 
* Its activity label. 
* An identifier of the subject who carried out the experiment.

###The Tidy Data Set
The tidy data set is created by running the run_analysis.R script, which downloads and cleans the raw data derived from the study. The tidy data set reads only variables dealing with calculations of either averages or standard deviation. It records an average of each measurement, per activity and subject (participant), across each of the variables. 

More detail on on the script is written within the [README file.](README.Rmd)

##Variables Dictionary
The tidy data set contains 180 observations across 88 variables, all of which have been defined here.

####subjectID    	
The numerical identifier for each participant (1:30.)

####activityType    	
Character vector of the name of the activity carried out (6 activities, including walking, walking 
upstairs, walking downstairs, sitting, standing and laying.)

_The following variables were all derived from the raw data recorded by the accelerometer and gyrocopes utilised in the study, (and written as they were cleaned by the tidy data set). Further transformations upon this data have also been recorded, including of magnitude, averages, etc._

####tBodyAccMeanX		
Averaging the signals in a signal window sample for body linear acceleration derived in time domain signals on the X axis.

####tBodyAccMeanY 		
Averaging the signals in a signal window sample for body linear acceleration derived in time domain signals on the Y axis.

####tBodyAccMeanZ		
Averaging the signals in a signal window sample for body linear acceleration derived in time domain signals on the Z axis.

####tGravityAccMeanX	
Averaging the signals in a signal window sample for gravitational acceleration of time domain signals on the X axis.

####tGravityAccMeanY	
Averaging the signals in a signal window sample for gravitational acceleration of time domain signals on the Y axis.

####tGravityAccMeanZ	
Averaging the signals in a signal window sample for gravitational acceleration of time domain signals on the Z axis.

####tBodyAccJerkMeanX	
Averaging the signals in a signal window sample for body linear acceleration derived in time to obtain jerk signals on the X axis.

####tBodyAccJerkMeanY	
Averaging the signals in a signal window sample for body linear acceleration derived in time to obtain jerk signals on the Y axis.

####tBodyAccJerkMeanZ	
Averaging the signals in a signal window sample for body linear acceleration derived in time to obtain jerk signals on the Z axis.

####tBodyGyroMeanX		
Averaging the signals in a signal window sample for body angular velocity derived in time domain signals on the X axis.

####tBodyGyroMeanY		
Averaging the signals in a signal window sample for body angular velocity derived in time domain signals on the Y axis.

####tBodyGyroMeanZ
Averaging the signals in a signal window sample for body angular velocity derived in time domain signals on the Z axis.

####tBodyGyroJerkMeanX
Averaging the signals in a signal window sample for body angular velocity derived in time to obtain jerk signals on the X axis.

####tBodyGyroJerkMeanY
Averaging the signals in a signal window sample for body angular velocity derived in time to obtain jerk signals on the Y axis.

####tBodyGyroJerkMeanZ
Averaging the signals in a signal window sample for body angular velocity derived in time to obtain jerk signals on the Z axis.

####tBodyAccMagMean
Averaging the signals in a signal window sample of the magnitude of body linear acceleration derived in time domain signals.

####tGravityAccMagMean
Averaging the signals in a signal window sample of the magnitude of gravitational acceleration derived in time domain signals.

####tBodyAccJerkMagMean
Averaging the signals in a signal window sample of the magnitude of body linear acceleration derived in time to obtain jerk signals.

####tBodyGyroMagMean
Averaging the signals in a signal window sample of the magnitude of body angular velocity derived in time domain signals.

####tBodyGyroJerkMagMean
Averaging the signals in a signal window sample of the magnitude of body angular velocity derived in time to obtain jerk signals.

####fBodyAccMeanX 
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration on the X axis.

####fBodyAccMeanY
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration on the Y axis.

####fBodyAccMeanZ
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration on the Z axis.

####fBodyAccMeanFreqX
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration on the X axis.

####fBodyAccMeanFreqY
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration on the Y axis.

####fBodyAccMeanFreqZ
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration on the Z axis.

####fBodyAccJerkMeanX
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the X axis.

####fBodyAccJerkMeanY
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the Y axis.

####fBodyAccJerkMeanZ
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the Y axis.

####fBodyAccJerkMeanFreqX 
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the X axis.

####fBodyAccJerkMeanFreqY
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the Y axis.

####fBodyAccJerkMeanFreqZ
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the Z axis.

####fBodyGyroMeanX
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity on the X axis.

####fBodyGyroMeanY
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity on the Y axis.

####fBodyGyroMeanZ
Averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity on the Z axis.

####fBodyGyroMeanFreqX
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body angular velocity on the X axis.

####fBodyGyroMeanFreqY
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body angular velocity on the Y axis.

####fBodyGyroMeanFreqZ
A weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body angular velocity on the Z axis.

####fBodyAccMagMean
The magnitude of averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration.

####fBodyAccMagMeanFreq
The magnitude of a weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration.

####fBodyBodyAccJerkMagMean
The magnitude of averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals.

####fBodyBodyAccJerkMagMeanFreq
The magnitude of a weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals.

####fBodyBodyGyroMagMean
The magnitude of averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity.

####fBodyBodyGyroMagMeanFreq
The magnitude of a weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body angular velocity.

####fBodyBodyGyroJerkMagMean
The magnitude of averaging the signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity to obtain jerk signals.

####fBodyBodyGyroJerkMagMeanFreq
The magnitude of a weighted average of the frequency components to obtain a mean frequency of a fast fourier transform applied to frequency domain signals of body angular velocity to obtain jerk signals.

####angletBodyAccMeanGravity
The angle between two vectors of averaging the signals in a signal window sample of body linear acceleration derived in time domain signals, and gravity.

####angletBodyAccJerkMeanGravityMean
The angle between two vectors of averaging the signals in a signal window sample of body linear acceleration derived in time to obtain jerk signals, and the mean value of gravity.

####angletBodyGyroMeanGravityMean
The angle between two vectors of averaging the signals in a signal window sample of body body angular velocity derived in time domain signals, and the mean value of gravity.

####angletBodyGyroJerkMeanGravityMean
The angle between two vectors of averaging the signals in a signal window sample of body angular velocity derived in time to obtain jerk signals, and the mean value of gravity.

####angleXGravityMean
The angle between two vectors, obtained by averaging the signals in a signal window sample for gravity on the X axis.

####angleYGravityMean
The angle between two vectors, obtained by averaging the signals in a signal window sample for gravity on the Y axis.

####angleZGravityMean
The angle between two vectors, obtained by averaging the signals in a signal window sample for gravity on the Z axis.

####tBodyAccStdX
Calculating the standard deviation of signals in a signal window sample for body linear acceleration derived in time domain signals on the X axis.

####tBodyAccStdY
Calculating the standard deviation of signals in a signal window sample for body linear acceleration derived in time domain signals on the Y axis.

####tBodyAccStdZ
Calculating the standard deviation of signals in a signal window sample for body linear acceleration derived in time domain signals on the Z axis.

####tGravityAccStdX
Calculating the standard deviation of signals in a signal window sample for gravitational acceleration of time domain signals on the X axis.

####tGravityAccStdY
Calculating the standard deviation of signals in a signal window sample for gravitational acceleration of time domain signals on the Y axis.

####tGravityAccStdZ
Calculating the standard deviation of signals in a signal window sample for gravitational acceleration of time domain signals on the Z axis.

####tBodyAccJerkStdX
Calculating the standard deviation of signals in a signal window sample for body linear acceleration derived in time to obtain jerk signals on the X axis.

####tBodyAccJerkStdY
Calculating the standard deviation of signals in a signal window sample for body linear acceleration derived in time to obtain jerk signals on the Y axis.

####tBodyAccJerkStdZ
Calculating the standard deviation of signals in a signal window sample for body linear acceleration derived in time to obtain jerk signals on the Z axis.

####tBodyGyroStdX
Calculating the standard deviation of signals in a signal window sample for body angular velocity derived in time domain signals on the X axis.

####tBodyGyroStdY
Calculating the standard deviation of signals in a signal window sample for body angular velocity derived in time domain signals on the Y axis.

####tBodyGyroStdZ
Calculating the standard deviation of signals in a signal window sample for body angular velocity derived in time domain signals on the Z axis.

####tBodyGyroJerkStdX
Calculating the standard deviation of signals in a signal window sample for body angular velocity derived in time to obtain jerk signals on the X axis.

####tBodyGyroJerkStdY
Calculating the standard deviation of signals in a signal window sample for body angular velocity derived in time to obtain jerk signals on the Y axis.

####tBodyGyroJerkStdZ
Calculating the standard deviation of signals in a signal window sample for body angular velocity derived in time to obtain jerk signals on the Z axis.

####tBodyAccMagStd
Calculating the standard deviation of signals in a signal window sample of the magnitude of body linear acceleration derived in time domain signals.

####tGravityAccMagStd
Calculating the standard deviation of signals in a signal window sample of the magnitude of gravitational acceleration derived in time domain signals.

####tBodyAccJerkMagStd
Calculating the standard deviation of signals in a signal window sample of the magnitude of body linear acceleration derived in time to obtain jerk signals.

####tBodyGyroMagStd
Calculating the standard deviation of signals in a signal window sample of the magnitude of body angular velocity derived in time domain signals.

####tBodyGyroJerkMagStd
Calculating the standard deviation of signals in a signal window sample of the magnitude of body angular velocity derived in time to obtain jerk signals.

####fBodyAccStdX
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration on the X axis.

####fBodyAccStdY
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration on the Y axis.

####fBodyAccStdZ
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration on the Z axis.

####fBodyAccJerkStdX
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the X axis.

####fBodyAccJerkStdY
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the Y axis.

####fBodyAccJerkStdZ
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals on the Z axis.

####fBodyGyroStdX
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity on the X axis.

####fBodyGyroStdY
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity on the Y axis.

####fBodyGyroStdZ
Calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity on the Z axis.

####fBodyAccMagStd
The magnitude of calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration.

####fBodyBodyAccJerkMagStd
The magnitude of calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body linear acceleration to obtain jerk signals.

####fBodyBodyGyroMagStd
The magnitude of calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity.

####fBodyBodyGyroJerkMagStd
The magnitude of  calculating the standard deviation of signals in a signal window sample of a fast fourier transform applied to frequency domain signals of body angular velocity to obtain jerk signals.

